print("My Daily Routine Printer")
print("Good Morning!")
print("Wake up Early in the Morning at 6:00 AM.")
print("Perform Yoga for Refreshing the Mind.")
print("Brush Your Teeth for next 2 minutes.")
print("Take Proper Bath with clean water and soap.")
print("Wear ironed and tidy uniform.")
print("Eat healthy breakfast.")
print("Get ready for School.")
print("Stay attentive during all classes.")
print("Have Lunch with the friends at School.")
print("After returning home, prioritize hygiene by becoming fresh.")
print("Complete the given homework smartly on time.")
print("Spend time 30-40 minutes on hobbies.")
print("Eat healthy Dinner.")
print("Prep for the Next day.")
print("Brush your teeth again before sleeping.")
print("Sleep Early at 10:00 pm for 8-9 hours for optimal brain functioning.")
print("Finally,end the day successfully by following the routine and refreshing for the next day!")